[package]
name = "composable-runtime"
version = "0.3.0"
edition = "2024"
description = "Modulewise Composable Runtime"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
oci-client = "0.15"
petgraph = "0.8"
rustyline = "17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
static-config = "0.2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"], optional = true }
toml = "0.9"
wac-graph = "0.9"
wac-types = "0.9"
wasm-pkg-client = "0.14"
wasmtime = "41"
wasmtime-wasi = "41"
wasmtime-wasi-config = "41"
wasmtime-wasi-http = "41"
wasmtime-wasi-io = "41"
wit-component = "0.244"
wit-parser = "0.244"

[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
wat = "1.244"

[features]
default = ["cli"]
cli = ["dep:tokio"]

[[bin]]
name = "composable-runtime"
path = "src/main.rs"
